the desktop version project
basem909/microverse-portofolio-project- pull request #6
Opened 2022-03-25 18:12 UTC by basem909

- this part of the portfolio project aims to turn the website into a responsive one that suits most of the screens 

- media queries added to the CSS style sheet to make the page responsive 

- some changes were made on the HTML file as well to fit the new approach to the responsive site.

- this part of the project is a solo coding part.

- languages used are HTML and CSS some functionality needs to be done through JS but it is not required at this level.

2022-03-25 18:38 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @basem909👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-25 18:38 UTC, thecodechaser commented on index.html
> +          <h2 class="header-project">projects</h2>
- [ ] Good job on the styles but for this project you are supposed to stick to the [Figma ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9)template as much as possible. Please use the correct font-weight for your `projects` and `about` headings and make sure they match the design on the [template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9).

### Your design
![image](https://user-images.githubusercontent.com/83803414/160180328-731a1d53-9ead-49cc-bd33-a6dffeb84b4d.png)

### Figma design
![image](https://user-images.githubusercontent.com/83803414/160180386-f82bbadb-deaa-4bcb-a21b-618681fdc499.png)

2022-03-25 18:38 UTC, thecodechaser commented on index.html
> +          <p class="contact-paragraph">
- [ ] Please make sure this section is in the center as on the design.

### Your design
![image](https://user-images.githubusercontent.com/83803414/160180767-c8753ab2-a102-4765-a8ed-e87d2919bd2c.png)

### Figma design
![image](https://user-images.githubusercontent.com/83803414/160180820-1bfc8780-9eda-475e-8400-9b44486834b6.png)

2022-03-25 18:38 UTC, thecodechaser commented on index.html
>              <h3 class="lang-header">languages</h3>
- [ ] Please place some left, right margins for this section to match the design.

### Your design

![image](https://user-images.githubusercontent.com/83803414/160181156-9432deb0-3f52-4fc5-bba9-e39007512acd.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/160181179-54f8ca8d-2233-44bd-8a1d-c086e0d9711a.png)

2022-03-25 18:38 UTC, thecodechaser commented on index.html
> +            Hello! I am a software developer! I can help you build a product,
- [ ] Please place some left margins for this section to match the design.

### Your design

![image](https://user-images.githubusercontent.com/83803414/160181531-48b1d0c9-780b-49be-a27c-7ccc842890af.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/160181576-e0fe8c17-ea8d-4265-9461-3a9b44e41f10.png)

2022-03-25 23:50 UTC, phelian23 requested changes
Hi @Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-25 23:50 UTC, phelian23 commented on styles.css
> +  }
- [ ] As requested by the previous reviewer, kindly ensure that your design matches the Figma template as much as possible. The projects grid is not properly arranged and some of the cards are stretched than they should, kindly fix this

| Your design | Figma template |
| ------------- | ------------- |
| ![Capture](https://user-images.githubusercontent.com/85095702/160215047-2ecf916e-73f9-4e6d-81fd-8a998bb06b1c.PNG) | ![figma](https://user-images.githubusercontent.com/85095702/160215087-dfe2c98a-42f7-4a3f-a106-c339e73d6cc1.PNG) |

2022-03-25 23:50 UTC, phelian23 commented on styles.css
> +  }
- [ ] As requested by the previous reviewer, kindly ensure that your design matches the Figma template as much as possible. The contact form is too wide and the `name` and `email` text field height is small compare to the template. please fix this.

| Your design | Figma template |
| ------------- | ------------- |
| ![Capture2](https://user-images.githubusercontent.com/85095702/160215359-6021287f-f5ab-4ea4-ba8b-a9c29b4fb68d.PNG) | ![figma2](https://user-images.githubusercontent.com/85095702/160215393-6c6caafc-6c41-48c0-94f2-d8d7de17c069.PNG) |

2022-03-26 01:32 UTC, Davidosky007 reviewed
Hello @basem909  👋,

_This is an additional review as a result of the second opinion request._

- The first requested change by @phelian23 wasnt mentioned by the first reviewer and as a result should have been OPTIONAL. but i will strongly suggest you fix the project cards some of them are a little bit over streched and the first card on hover the project should display to the right. below is a screen shot to highlight the affected sections .
- For the second requested change which is the contact form kindly adjust the width of the input filelds below is a screenshot of how centered the width of that section should look 
![image](https://user-images.githubusercontent.com/52497246/160219286-f4eec8ee-cfde-40df-9be7-add358c7cd0d.png)

![image](https://user-images.githubusercontent.com/52497246/160219096-9875bd0f-302d-4963-a3a4-872149ca305c.png)
## NOTE : Kindly note that it is part of the learning objectives for this milestone to Understand how to parse a Figma design to create a UI. so therefore it is an important requirement that your design looks as much as possible to the figma design 🙏 

As this was the only reason that your project was not approved kindly fix the neccessary changes and it will be approved as soon as possible. 
Please ask for another review in your Dashboard and the next Code Reviewer will review it accordingly 👍 

Keep rocking 🚀!

2022-03-26 08:17 UTC, FrederickMih approved these changes
# Status : Approved :medal_military: :tada: 

Hi @basem909 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-26 19:22 UTC, basem909 commented
the desktop version adds media query to the site to make it responsive to different devices and browsers

2022-03-26 19:22 UTC, merged